config: |
  -

  Panamera 4 Executive

  IMAGE
  https://s.aolcdn.com/dims-global/dims3/GLOB/legacy_thumbnail/916x515/quality/95/https://s.blogcdn.com/slideshows/images/slides/715/583/5/S7155835/slug/l/roadster-front-34-1.jpg
  A picture of a car

  -

  Details {{ user.name }}

  TEXT
  Owner "{{ user.name }}" can be contacted via {{ user.email }}. This ticket has the subject of "{{ ticket.subject }}".

  TABLE
  Power, Acceleration, Drive
  243 kW, 2.3 Seconds, All Wheel

  BUTTON
  Show Details {{ user.name }}

  -

  Optional Extras

  TABLE
  Winter Wheels
  20 Inch Panamera

  -

  Find a Service Centre

  MAP
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2492.0791598488554!2d-0.483142684169452!3d51.346454979609156!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4876761d51b1c793%3A0xa1b9f87e35b40c23!2sPorsche+Service+Centre+Brooklands!5e0!3m2!1sen!2suk!4v1511345317754" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

  -

  Schedule an Inspection

  DATE
  Select a Date...

  INPUT
  Additional Notes...

  BUTTON
  Book

  -

  Additional Information

  TEXT
  The previous owner took care of this car for the past 5 years.